language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - USE_CMAKE=YES
  - USE_CMAKE=NO

addons:
  apt:
    packages:
      - texinfo

script:
  - mkdir build
  - cd build
  - if [ $USE_CMAKE == "YES" ] ; then cmake ../ ; fi
  - if [ $USE_CMAKE == "NO" ] ; then pushd ../ ; autoreconf -i ; popd; fi
  - if [ $USE_CMAKE == "NO" ] ; then ../configure ; fi
  - make
  - make check
