# This is the configuration file for AppVeyor builds.
# Look at the following for reference:
# https://www.appveyor.com/docs/appveyor-yml

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  matrix:
  - platform: msvc
  - platform: vs2008_32
  - platform: vs2010_32
  - platform: vs2012_32
  - platform: vs2012_64
  - platform: vs2013_64
  - platform: vs2015_64
  - platform: vs2017_64
  - platform: cygwin
  - platform: mingw32
  - platform: mingw64msys

# scripts that are called at very beginning, before repo cloning
# init:

# clone directory
clone_folder: c:\projects\check

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  - cd c:\projects\check
  # Remove the following from the path, as it will interfere with
  # the MinGW builds
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %platform%==msvc call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - if %platform%==msvc cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs2008_32 cmake -G "Visual Studio 9 2008 Win32" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs2010_32 cmake -G "Visual Studio 10 2010 Win32" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs2012_32 cmake -G "Visual Studio 11 2012 Win32" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs2012_64 cmake -G "Visual Studio 11 2012 Win64" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs2013_64 cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs2015_64 cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs2017_64 cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==cygwin set PATH=C:\cygwin\bin;%PATH%
  - if %platform%==cygwin bash -c "autoreconf -i"
  - if %platform%==cygwin bash -c "./configure"
  - if %platform%==mingw32 set PATH=C:\MinGW\bin;%PATH%
  - if %platform%==mingw32 cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==mingw64msys set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - if %platform%==mingw64msys bash -c "autoreconf -i"
  - if %platform%==mingw64msys bash -c "./configure"

build_script:
  # build code and unit tests
  - if %platform%==msvc nmake
  - if %platform%==vs msbuild "ALL_BUILD.vcxproj"
  - if %platform%==cygwin bash -c "make"
  - if %platform%==mingw32 mingw32-make
  - if %platform%==mingw64msys bash -c "make"

test_script:
  # run unit tests
  - echo Running unit tests...
  - if %platform%==msvc nmake test VERBOSE=1 CTEST_OUTPUT_ON_FAILURE=TRUE
  - if %platform%==vs ctest --extra-verbose -C Release
  - if %platform%==cygwin bash -c "make check"
  - if %platform%==mingw32 tests\check_check.exe
  - if %platform%==mingw64msys bash -c "tests/check_check"

on_finish:
  - if %platform%==cygwin bash -c "cat tests/test-suite.log || true"
