# This is the configuration file for AppVeyor builds.
# Look at the following for reference:
# https://www.appveyor.com/docs/appveyor-yml

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#


environment:
  matrix:
  - platform: msvc
  - platform: vs
    vsversion: 2008
    arch: x86
  - platform: vs
    vsversion: 2010
    arch: x86
  - platform: vs
    vsversion: 2012
    arch: x86
  - platform: vs
    vsversion: 2013
    arch: x86
  - platform: vs
    vsversion: 2015
    arch: x86
  - platform: vs
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    vsversion: 2017
    arch: x86
  - platform: vs
    vsversion: 2010
    arch: x64
  - platform: vs
    vsversion: 2012
    arch: x64
  - platform: vs
    vsversion: 2013
    arch: x64
  - platform: vs
    vsversion: 2015
    arch: x64
  - platform: vs
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    vsversion: 2017
    arch: x64
  - platform: vs
    vsversion: 2012
    arch: ARM
  - platform: vs
    vsversion: 2013
    arch: ARM
  - platform: vs
    vsversion: 2015
    arch: ARM
  - platform: vs
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    vsversion: 2017
    arch: ARM
  - platform: cygwin
  - platform: mingw32
  - platform: mingw64msys

# scripts that are called at very beginning, before repo cloning
# init:

# clone directory
clone_folder: c:\projects\check

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  - cd c:\projects\check
  # Remove the following from the path, as it will interfere with
  # the MinGW builds
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if %platform%==msvc call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - if %platform%==msvc cmake -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==vs (
      set "makecommand=Visual Studio"
    )
  - if %vsversion%==2005 (
      set "makecommand=%makecommand% 8 %vsversion%"
    )
  - if %vsversion%==2008 (
      set "makecommand=%makecommand% 9 %vsversion%"
    )
  - if %vsversion%==2010 (
      set "makecommand=%makecommand% 10 %vsversion%"
    )
  - if %vsversion%==2012 (
      set "makecommand=%makecommand% 11 %vsversion%"
    )
  - if %vsversion%==2013 (
      set "makecommand=%makecommand% 12 %vsversion%"
    )
  - if %vsversion%==2015 (
      set "makecommand=%makecommand% 14 %vsversion%"
    )
  - if %vsversion%==2017 (
      set "makecommand=%makecommand% 15 %vsversion%"
    )
  - if %arch%==x64 (
      set "makecommand=%makecommand% Win64"
    )
  - if %arch%==ARM (
      set "makecommand=%makecommand% ARM"
    )
  - if %platform%==vs cmake -G "%makecommand%" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==cygwin set PATH=C:\cygwin\bin;%PATH%
  - if %platform%==cygwin bash -c "autoreconf -i"
  - if %platform%==cygwin bash -c "./configure"
  - if %platform%==mingw32 set PATH=C:\MinGW\bin;%PATH%
  - if %platform%==mingw32 cmake -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=%P%
  - if %platform%==mingw64msys set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - if %platform%==mingw64msys bash -c "autoreconf -i"
  - if %platform%==mingw64msys bash -c "./configure"

#Platforms supported by AppVeyor, as of 2017-08-28
#see https://www.appveyor.com/docs/build-environment/
#Generators
#  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
#                                 Optional [arch] can be "Win64" or "ARM".
#  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
#                                 Optional [arch] can be "Win64" or "ARM".
#  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
#                                 Optional [arch] can be "Win64" or "ARM".
#  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
#                                 Optional [arch] can be "Win64" or "ARM".
#  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
#                                 Optional [arch] can be "Win64" or "IA64".
#  Visual Studio 9 2008         = Generates Visual Studio 2008 project files.
#  NMake Makefiles              = Generates NMake makefiles.
#  MinGW Makefiles              = Generates a make file for use with
#                                 mingw32-make.


build_script:
  # build code and unit tests
  - if %platform%==msvc nmake
  - if %platform%==vs msbuild /p:Platform=%arch% "ALL_BUILD.vcxproj"
  - if %platform%==cygwin bash -c "make"
  - if %platform%==mingw32 mingw32-make
  - if %platform%==mingw64msys bash -c "make"

test_script:
  # run unit tests
  - echo Running unit tests...
  - if %platform%==msvc nmake test VERBOSE=1 CTEST_OUTPUT_ON_FAILURE=TRUE
  - if %platform%==vs ctest --extra-verbose -C Release
  - if %platform%==cygwin bash -c "make check"
  - if %platform%==mingw32 tests\check_check.exe
  - if %platform%==mingw64msys bash -c "tests/check_check"

on_finish:
  - if %platform%==cygwin bash -c "cat tests/test-suite.log || true"

