name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux_autotools_default_args:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doc packages
      run: sudo apt-get install -y texlive texinfo texi2html doxygen
    - name: create configure
      run: autoreconf -i
    - name: configure default
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install

  build_linux_autotools_other_args:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doc packages
      run: sudo apt-get install -y texlive texinfo texi2html doxygen
    - name: create configure
      run: autoreconf -i
    - name: configure default
      run: ./configure --disable-fork --disable-subunit --enable-snprintf-replacement --enable-timer-replacement
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: sudo make install

  build_linux_autotools_prereleasecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doc packages
      run: sudo apt-get install -y texlive texinfo texi2html doxygen
    - name: create configure
      run: autoreconf -i
    - name: configure default
      run: ./configure
    - name: make prereleasecheck
      run: make prereleasecheck

  build_linux_autotools_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doc packages
      run: sudo apt-get install -y texlive texinfo texi2html doxygen
    - name: create configure
      run: autoreconf -i
    - name: configure default
      run: ./configure
    - name: make docs
      run: make doc/check_html
    - name: make doxygen 
      run: make doc/doxygen

  build_linux_autotools_example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doc packages
      run: sudo apt-get install -y texlive texinfo texi2html doxygen
    - name: create configure
      run: autoreconf -i
    - name: configure default
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: create configure example
      working-directory: doc/example
      run: autoreconf -i
    - name: configure example
      working-directory: doc/example
      run: ./configure
    - name: build example
      working-directory: doc/example
      run: make 
    - name: test example
      working-directory: doc/example
      run: make check
    
  build_linux_cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake cversion
      run: cmake --version
    - name: create configs
      run: cmake .
    - name: make
      run: make
    - name: unit tests
      run: ctest -V
    - name: make install 
      run: sudo make install
  
  build_linux_scanbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install scan-build packages
      run: sudo apt-get install -y clang-tools
    - name: create configure
      run: autoreconf -i
    - name: configure
      run: scan-build ./configure --enable-snprintf-replacement --enable-timer-replacement --disable-build-docs
    - name: make
      run: scan-build -o clang make 
    - name: check for issues
      run: |
        if [ -n "$(find clang -type f)" ]; then
          echo "scan-build found potential issues"
          find clang -type f -print -exec cat \{} \;
          exit 1
        fi
